// <auto-generated />
namespace OrderBot.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Extendedsupport : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Extendedsupport));
        
        string IMigrationMetadata.Id
        {
            get { return "201810071638381_Extended support"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
